---
name: Build

on:
  push:
    branches: [main]
    paths:
      - "CMakeLists.txt"
      - "src/**"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [main]
    paths:
      - "CMakeLists.txt"
      - "src/**"
      - ".github/workflows/build.yml"
  schedule:
    - cron: "37 5 * * 3,6"

permissions: read-all

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        qtver: ['5.15.2', '6.0.3']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{runner.os}}-${{matrix.qtver}}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{matrix.qtver}}
          cached: ${{steps.cache-qt.outputs.cache-hit}}
          setup-python: false

      - name: Configure Release
        run: cmake -B ${{github.workspace}}/build-release -DCMAKE_BUILD_TYPE=Release

      - name: Configure Debug
        run: cmake -B ${{github.workspace}}/build-debug -DCMAKE_BUILD_TYPE=Debug

      - name: Build Release
        run: cmake --build ${{github.workspace}}/build-release --config Release

      - name: Build Debug
        run: cmake --build ${{github.workspace}}/build-debug --config Debug
