name: "Package"

on: push

env:
  BUILD_TYPE: Release

jobs:
  tarpkg:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Create version.txt
        run: git describe --tags --match 'v*' >version.txt

      - name: Create tarball
        shell: bash
        run: |
          NAME=nb-dashcam-tools-$(git describe --tags --match 'v*' --abbrev=0 | cut -c2-)
          tar -C "${{github.workspace}}" -czf "${{runner.temp}}/$NAME.tgz" --exclude-vcs --transform "s,^\\.,$NAME," .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "${{runner.temp}}/nb-dashcam-tools-*.tgz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  winpkg:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.0.3'

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DWIN_INSTALL_FFMPEG=ON -DWIN_CREATE_SETUP=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Install
        run: cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}/deploy --config ${{env.BUILD_TYPE}}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{github.workspace}}/nb-dashcam-tools-setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  rpmpkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create version.txt
        run: git describe --tags --match 'v*' >version.txt

      - name: Build Container
        run: docker build -t builder:latest "${{github.workspace}}/.github/docker/rpmpkg"

      - name: Create RPM
        shell: bash
        run: |
          VER=$(git describe --tags --match 'v*' --abbrev=0 | cut -c2-)
          NAME=nb-dashcam-tools-$VER
          tar -C "${{github.workspace}}" -czf "${{runner.temp}}/$NAME.tgz" --exclude-vcs --transform "s,^\\.,$NAME," .
          docker run --rm -v "${{runner.temp}}:/mnt" -e "VER=$VER" -e "SRC=$NAME.tgz" builder:latest

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "${{runner.temp}}/nb-dashcam-tools-*.rpm"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
